browser=chrome
env=qa
qa.base_url=https://eventhub.rahulshettyacademy.com/login
prod.base_url=https://eventhub.rahulshettyacademy.com/login
dev.base_url=https://www.google.co.in

username=gaurav.rajput04@gmail.com
password=Sahaj@224565

Headless=false